
# Site settings
title: Pith
email: kevin.e.roark@gmail.com
description: >
  Pith is Jonah Reider's NYC supper club and brand of events
permalink: /:categories/:title
baseurl: ""
future: true
url: "http://www.pith.space"
twitter_username: limp__biscuit
github_username: kevin-roark
gems:
  - octopress-autoprefixer
