defaults:
    - scope:
          path: ""
          type: "posts"
      values:
          layout: null
          permalink: /:year-:month-:day-:title
    - scope:
          path: ""
          type: "pages"
      values:
          layout: "page"
